name: PythonImpliment

on:
  push:
  workflow_dispatch: #手動実行

jobs:
  PythonHelloWorld:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4 #アクションの呼び出し
                                  #ワークフローをトリガにしたリポジトリとブランチのみチェックアウトする
      - run: |
          ls -a
          echo "" 
          git branch -a
      - run: python ./tools/hellow.py